FROM ubuntu:24.04
RUN apt update && apt install -y build-essential libapt-pkg-dev nlohmann-json3-dev libcurl4-openssl-dev clang make
COPY ./header.hpp /app/
COPY ./main.cpp /app/
COPY ./makefile /app/
WORKDIR /app
RUN make
